# http://travis-ci.org/#!/ipython/ipython
language: python

cache:
    directories:
        - $HOME/.cache/pip
python:
    - 3.6

env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/pandoc:$PATH
  matrix:
    - GROUP=python

before_install:
    - pip install --upgrade pip
    - |
      if [[ $GROUP == docs ]]; then
        pip install -r docs/doc-requirements.txt
        pip install nbval
      fi

install:
    - pip install .[test]
    - wget https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb && sudo dpkg -i pandoc-1.19.1-1-amd64.deb


script:
    - jupyter kernelspec list
    - |
      symlinks=$(find . -type l| grep -v './git-hooks')
      if [[ $(echo $symlinks) ]]; then
          echo "Repository contains symlinks which won't work on windows:"
          echo $symlinks
          echo ""
          false
      else
          true
      fi
    - 'if [[ $GROUP == python ]]; then py.test --cov=jupyter_server; fi'
    - |
      if [[ $GROUP == docs ]]; then
        EXIT_STATUS=0

        make -C docs/ html || EXIT_STATUS=$?

        if [[ $TRAVIS_EVENT_TYPE == cron ]]; then
          make -C docs/ linkcheck || EXIT_STATUS=$?;
        fi

        pytest --nbval --current-env docs || EXIT_STATUS=$?
        exit $EXIT_STATUS
      fi


matrix:
    include:
        - python: 3.6
          env: GROUP=python
        - python: 3.5
          env: GROUP=python
        - python: "3.7-dev"
          env: GROUP=python
        - python: 3.6
          env: GROUP=docs

after_success:
    - codecov
