# miniconda bootstrap from conda-forge recipe
matrix:
  fast_finish: true

environment:
  matrix:
    - CONDA_PY: 36
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"

platform:
  - x64

build: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda config --set show_channel_urls true
  - cmd: conda config --add channels conda-forge
  #- cmd: conda update --yes --quiet conda
  - cmd: conda install --file requirements.txt
  - cmd: pip install .[test]

test_script:
  - py.test
